### ISSUE TITLE
Create cycle detection for graph

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [leandroBorgesFerreira/dag-command#8]
If the user crates a circular dependency in the gradle modules, a stackoverflow error happens in the code, which is not very informative to the end users. So a cycle detection should be created so the library can respond with a more interesting error message.

**Comment by StefMa** [comment]
This is fixed with 1.11.0 right?
So it can be closed?

**Comment by leandroBorgesFerreira** [comment]
Indeed. I forgot to close it.
